import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // next-env.d.ts is generated by `next build` and must not be edited;
  // linting it only ever reports on Next.js's own output.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts"] },
];

export default config;
