"""baseline: users, projects, outputs, jobs, settings, audit

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-08-30 05:09:37.500461
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.Float(), nullable=False),
    sa.Column('user', sa.String(length=64), server_default='', nullable=False),
    sa.Column('ip', sa.String(length=64), server_default='', nullable=False),
    sa.Column('method', sa.String(length=8), server_default='', nullable=False),
    sa.Column('path', sa.String(length=300), server_default='', nullable=False),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_at', 'audit_log', [sa.text('at DESC')], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('pw_salt', sa.String(length=64), nullable=False),
    sa.Column('pw_hash', sa.String(length=128), nullable=False),
    sa.Column('pw_changed_at', sa.Float(), nullable=True),
    sa.Column('token_serial', sa.Integer(), server_default='0', nullable=False),
    sa.Column('role', sa.String(length=16), server_default='editor', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('video_key', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('audio_key', sa.String(length=512), nullable=True),
    sa.Column('schema_version', sa.Integer(), server_default='4', nullable=False),
    sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_projects_owner_updated', 'projects', ['owner_id', sa.text('updated_at DESC')], unique=False
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='50', nullable=False),
    sa.Column('lane', sa.String(length=16), server_default='net', nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=48), server_default='', nullable=False),
    sa.Column('message', sa.Text(), server_default='', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('no_retry', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('heartbeat_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_jobs_claimable', 'jobs', ['state', 'priority', 'created_at'], unique=False)
    op.create_index('ix_jobs_project', 'jobs', ['project_id', sa.text('created_at DESC')], unique=False)
    op.create_table('outputs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('r2_key', sa.String(length=512), nullable=False),
    sa.Column('srt_key', sa.String(length=512), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outputs_project', 'outputs', ['project_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outputs_project', table_name='outputs')
    op.drop_table('outputs')
    op.drop_index('ix_jobs_project', table_name='jobs')
    op.drop_index('ix_jobs_claimable', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_projects_owner_updated', table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index('ix_audit_at', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
